apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-demo-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/piyushpawar-syvora/nginx-demo.git
    targetRevision: HEAD

  destination: 
    server: https://kubernetes.default.svc
    namespace: argocd-demo

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true